##Local Standalone Run
services:
  mysql-storage-local-test:
    container_name: mysql-storage-local-test
    image: mysql:8.0
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_0900_ai_ci
      --init-connect='SET NAMES utf8mb4;'
      --skip-character-set-client-handshake
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: ${TZ}
    ports:
      - "3306:3306"
    networks:
      - storage-ms-local-test
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/.data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 30s
      retries: 8
  storage-ms-local-test:
    container_name: storage-ms-local-test
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      # EUREKA_SERVER_URL: "http://${SERVICE_REGISTRY_HOSTNAME:-host.docker.internal}:${SERVICE_REGISTRY_PORT:-8761}/eureka/"
      SERVER_PORT: ${SERVER_PORT:-8080}
      DB_URL: "r2dbc:mysql://mysql-storage-local-test:3306/${DB_NAME}"
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      EUREKA_CLIENT_ENABLE: false
    depends_on:
      mysql-storage-local-test:
        condition: service_healthy
    networks:
      - storage-ms-local-test
networks:
  storage-ms-local-test:
    driver: bridge
