server:
  port: ${SERVER_PORT:-8080}
application:
  name: "storage-ms"
  version: "1.0.0"
  api:
    endpoint: /api/storage
    version: v1
spring:
  application:
    name: storage-ms
  r2dbc:
    pool:
      enable: true
      initial-size: 10
      max-size: 20
    url: ${R2DBC_URL:r2dbc:mysql://host.docker.internal:3306/storage}
    username: root
    password: ${MYSQL_ROOT_PASSWORD:changeInProd!}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://host.docker.internal:8761/eureka/}
    renewal-interval-in-seconds: 30 # Heartbeat every 30 seconds
    instance-info-replication-interval-seconds: 60
    lease-expiration-duration-in-seconds: 90
  instance:
    prefer-ip-address: true
